hack/urls.py
from django.contrib import admin
from django.urls import path,include
from user import views as user_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',user_views.register,name="register"),
    path('login/',user_views.login,name="login"),
    path('registered/',user_views.index,name="index"),
    path('main',include('main.urls'))
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

main/urls.py
from . import views
from django.urls import path
app_name='main'
urlpatterns = [
    # /food/
    path('',views.main,name='main'),
    path('index/',views.index_main,name='index_main'),
    path('login_0/',views.login_0,name="login_0"),
    path('about/',views.about,name="about"),
    path('cleaner/',views.cleaner,name="cleaner"),
    path('cook/',views.cook,name="cook"),
    path('plumber/',views.plumber,name="plumber"),
    path('elec/',views.elec,name="elec"),
    path('carp/',views.carp,name="carp"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Profile(models.Model):


    user_name=models.OneToOneField(User,on_delete=models.CASCADE,default=1)
    gender=models.CharField(max_length=10,null=True,blank=True)
    email=models.CharField(max_length=200,null=True,blank=True)
    age=models.IntegerField(null=True,blank=True)
    mobile=models.IntegerField(null=True,blank=True)
    city=models.CharField(max_length=200,null=True,blank=True)
    profession=models.CharField(max_length=20,null=True,blank=True)
    fees=models.FloatField(null=True,blank=True)
    profile_image = models.ImageField(upload_to='images/', blank=True, null=True,default='image.jpg')

    @property
    def imageURL(self):
        try:
            url=self.profile_image.url
        except:
            url=''
        return url  
    def __str__(self):
        return self.user_name.username

main/forms.py
from django import forms
from .models import Profile

class Profile_form(forms.ModelForm):
    class Meta:
        model=Profile
        fields=['user_name','email','mobile','profession']

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    class Meta:
        model=User
        fields=['username','first_name','last_name','password1','password2']

main/views.py
from django.shortcuts import render,redirect
# Create your views here.
from django.contrib.auth.models import User
from .forms import Profile_form
from .models import Profile
def main(request):
    return render(request,'main/main.html',{})

def index_main(request):
    return render(request,'main/index_main.html',{})

def about(request):
    return render(request,'main/about.html',{})

def cleaner(request):
    cleaner_list=Profile.objects.filter(profession="Cleaner")
    return render(request,'main/Cleaner.html',{'cleaner_list':cleaner_list})

def cook(request):
    cook_list=Profile.objects.filter(profession="Cook")
    return render(request,'main/Cook.html',{'cook_list':cook_list})

def plumber(request):
    plumber_list=Profile.objects.filter(profession="Plumber")
    return render(request,'main/Plumber.html',{'plumber_list':plumber_list})

def elec(request):
    elec_list=Profile.objects.filter(profession="Electrician")
    return render(request,'main/Electrician.html',{'elec_list':elec_list})

def carp(request):
    carp_list=Profile.objects.filter(profession="Carpenter")
    return render(request,'main/carpenter.html',{'carp_list':carp_list})

# def login_0(request):
#     form=Profile_form(request.POST or None)
#     if form.is_valid():
#         profile=form.save(commit=False)
#         profile.user_name=request.user
#         profile.save()
#         return redirect('index')
    
#     return render(request,'main/login_0.html',{'form':form})
def login_0(request):
    if request.method == 'POST':
        gender=request.POST.get('gender')
        email = request.POST.get('email')
        age = request.POST.get('age')
        city = request.POST.get('city')
        profession = request.POST.get('profession')
        mobile = request.POST.get('mobile')
        fees=request.POST.get('fees')
        
        # Create a new Profile object and save it to the database
        profile = Profile(user_name=request.user, email=email, age=age, city=city, profession=profession, mobile=mobile,fees=fees,gender=gender)
        profile.save()
        
        return redirect('index')

    # If the request method is not POST or form is not valid, render the template with the form
    form = Profile_form()
    return render(request, 'main/login_0.html', {'form': form})

user/views.py
from django.shortcuts import render,redirect
# from .forms import RegisterForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_tobe
from django.contrib.auth import logout as logout_tobe
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import random
# Create your views here.
from django.contrib.auth.models import User
import random
from .forms import RegisterForm 

# def register(request):
#     if request.method == "POST":
#         email = request.POST.get('email')
#         # Check if user with this email already exists
#         if User.objects.filter(username=email).exists():
#             return render(request, 'user/register.html', {'error': 'Email is already registered'})

#         first_name = request.POST.get('first_name')
#         last_name = request.POST.get('last_name')
#         mobile = request.POST.get('mobile')
#         profession = request.POST.get('profession')
#         password1 = request.POST.get('password1')
#         password2 = request.POST.get('password2')
#         # profile=Profile.objects.get_or_create(profession=profession,mobile=mobile)
#         if password1 == password2:
#             user = User.objects.create_user(username=email, email=email, password=password1,
#                                             first_name=first_name, last_name=last_name)
#             # profile = Profile.objects.create(user=user, profession=profession, mobile=mobile)

#             return redirect('login')
#         else:
#             return render(request, 'user/register.html', {'error': 'Passwords do not match'})

#     return render(request, 'user/register.html')

def register(request):
    if request.method=='POST':
        form=RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            # username=form.cleaned_data.get('username')
            # messages.success(request,f'Welcome {username}, your account is created')
            return redirect('login')
    else:
        form=RegisterForm()
    return render(request,'user/register.html',{'form':form})


def login(request):
    if request.method=="POST":
        username = request.POST.get('username')
        password = request.POST.get('password') 
        user = authenticate(request, username=username, password=password) 
        if user is not None:
            login_tobe(request,user)
            return redirect('main:login_0')
        else:
            return redirect('login')
    else:
        return render(request,'user/login.html',{})
    

def index(request):
    return render(request,'user/index.html')

main/templates/main/Cleaner.html
<!-- {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style_cleaner.css' %}">
</head>
<body>
    <div class="container">
        <div class="top">
            <div class="top-left">
                <a href="{% url 'main:index_main' %}" class="prev-page"><p>&larr; Prev. Page</p></a>
            </div>
        </div>
        <div class="cleaners-first-row">
            {% for item in cleaner_list %}
            <div class="cleaner-1">
                <div class="cleaner-left">
                    <h1 class="name">{{ item.user_name.username }}</h1>
                    <div class="age">Age: <span>24</span></div>
                    <div class="state">State: <span>Haryana</span> </div>
                    <div class="rating">Rating: <span>4.7</span></div>
                    <button class="contact">Book Appointment</button>
                </div>
                <div class="cleaner-right">
                    <img src="{% static 'images/cleaner-1.png' %}" alt="Error" height="200px">
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html> -->

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style_cleaner.css' %}">
</head>
<body>
    <div class="container">
        <div class="top">
            <div class="top-left">
                <a href="{% url 'main:index_main' %}" class="prev-page"><p>&larr; Prev. Page</p></a>
            </div>
        </div>
        <div class="cleaners">
            {% for item in cleaner_list %}
            <div class="cleaner-1">
                <div class="cleaner-right">
                    <img src="{{ item.imageURL }}" alt="Error" height="200px">
                </div>
                <div class="cleaner-left">
                    <h1 class="name" style="font-size: 2.5rem;">{{item.user_name.username}}</h1>
                    <div class="money">Gender- {{item.gender}}<span></span></div>
                    <div class="age">Age- {{item.age}} <span></span></div>
                    <div class="mobile_no">Contact- {{item.mobile}}<span></span></div>
                    <div class="city">City- {{item.city}}<span></span></div>
                    <div class="money">Fees- ₹{{item.fees}}<span></span></div><br>
                    <button class="contact">Book Appointment</button>
                </div>
            </div>
            {% endfor %}
            
        </div>
    </div>
</body>
</html>

main/templates/main/about.html
<!-- {% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree&family=Libre+Baskerville&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style_about.css' %}">
    
    <title>About Us</title>

</head>
<body>
    <div class="container">

        <div class="nav-bar">
            <div class="nav-left">
                <img src="{% static 'images/trident works-fotor-bg-remover-20230818221358.png' %}" alt="Error" class="web-logo">
            </div>
            <div class="nav-right">
                <div class="home">
                    <a href="{% url 'main:index_main' %}">Home</a>
                </div>
                <div class="about">
                    <a href="{% url 'main:about' %}">
                        Our Team
                    </a>
                </div>
                <div class="services">
                    <a href="#bokmark">
                        Services
                    </a>
                </div>
            </div>
        </div>
    
        <section id="aboutus">
                <h1>About Us</h1>
                <p>Welcome to our team's website! We are a group of passionate individuals...</p>
            
        </section>
    
        <section id="team">
            <div class="container">
                <h1>Our Team</h1>
                <div class="people">
                    <div class="team-member">
                        <img src="{% static 'images/krish.jpg' %}" alt="Team Member 1">
                        <h2>Krish Chitlangia</h2>
                        <p>Role: Backend Developer</p>
                    </div>
                    <div class="team-member">
                        <img src="{% static 'images/avinash.jpg' %}" alt="Team Member 2">
                        <h2>Avinash Krishnan</h2>
                        <p>Role: Frontend Developer</p>
                    </div>
                    <div class="team-member">
                        <img src="{% static 'images/krish.jpg' %}" alt="Team Member 3">
                        <h2>Krish Chitlangia</h2>
                        <p>Role: Backend Developer</p>
                    </div>
                    <div class="team-member">
                        <img src="{% static 'images/avinash.jpg' %}" alt="Team Member 4">
                        <h2>Avinash Krishnan</h2>
                        <p>Role: Frontend Developer</p>
                    </div>
    
                </div>
            </div>
        </section>
    
        <section id="contact">
            <div class="container">
                <h1>Contact Us</h1>
                <p>If you have any questions or inquiries, feel free to contact us at <a href="mailto:info@example.com">info@example.com</a>.</p>
            </div>
        </section>
    </div>

    <script src="{% static 'js/script.js' %}"></script>
</body>
</html> -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree&family=Libre+Baskerville&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style_about.css' %}">
    
    <title>About Us</title>

</head>
<body>
    <div class="container">

        <div class="nav-bar">
            <div class="nav-left">
                <img src="{% static 'images/trident works-fotor-bg-remover-20230818221358.png' %}" alt="Error" class="web-logo">
            </div>
            <div class="nav-right">
                <div class="home">
                    <a href="{% url 'main:index_main' %}">Home</a>
                </div>
                <div class="about">
                    <a href="{% url 'main:about' %}">
                        Our Team
                    </a>
                </div>
                <div class="services">
                    <a href="{% url 'main:index_main' %}">
                        Services
                    </a>
                </div>
            </div>
        </div>
    
        <section id="aboutus">
                <h1>About Us</h1>
                <p>Welcome to our team's website! We are a group of passionate individuals...</p>
            
        </section>
    
        <section id="team">
            <div class="container">
                <h1 class="our_team">Our Team</h1>
                <div class="people">
                    <div class="left">
                        <div class="team-member">
                            <img src="{% static 'images/krish.jpg' %}" alt="Team Member 1" class="ourimg krish">
                            <h2>Krish Chitlangia</h2>
                            <p>Role: Backend Developer</p>
                            <div class="card1">
                                <div class="insta">
                                    <a href="www.instagram.com">
                                        <img src="/static/images/instagram.png" alt="Error" class="imagportion" id="insta">
                                    </a>
                                </div>
                                <div class="linkedin">
                                    <a href="www.linkedin.com">
                                        <img src="/static/images/linkedin.png" alt="Error" class="imagportion" id="twitt">
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="team-member">
                            <img src="{% static 'images/arjun.jpg' %}" alt="Team Member 4" class="ourimg arjun">
                            <h2>Arjun Tyagi</h2>
                            <p>Role: Design and Development</p>
                            <div class="card2">
                                <div class="insta">
                                    <a href="">
                                        <img src="/static/images/instagram.png" alt="Error" class="imagportion" id="insta">
                                    </a>
                                </div>
                                <div class="linkedin">
                                    <a href="">
                                        <img src="/static/images/linkedin.png" alt="Error" class="imagportion" id="twitt">
                                    </a>
                                </div>
                            </div>
                        </div>
                        
                    </div>
                    <img src="{% static 'images/logo_cube.png' %}"alt="Error" class="logo-cube">
                    <div class="right">
                        <div class="team-member">
                            <img src="{% static 'images/avinash.jpg' %}" alt="Team Member 2" class="ourimg avinash">
                            <h2>Avinash Krishnan</h2>
                            <p>Role: Frontend Developer</p>
                            <div class="card3">
                                <div class="insta">
                                    <a href="">
                                        <img src="/static/images/instagram.png" alt="Error" class="imagportion" id="insta">
                                    </a>
                                </div>
                                <div class="linkedin">
                                    <a href="">
                                        <img src="/static/images/linkedin.png" alt="Error" class="imagportion" id="twitt">
                                    </a>
                                </div>
                            </div>
                        </div>
                        
                        <div class="team-member">
                            <img src="{% static 'images/aryan.jpg' %}" alt="Team Member 3" class="ourimg aryan">
                            <h2>Aryan Tyagi</h2>
                            <p>Role: Product Manager</p>
                            <div class="card4">
                                <div class="insta">
                                    <a href="">
                                        <img src="/static/images/instagram.png" alt="Error" class="imagportion" id="insta">
                                    </a>
                                </div>
                                <div class="linkedin">
                                    <a href="">
                                        <img src="/static/images/linkedin.png" alt="Error" class="imagportion" id="twitt">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    
        <section id="contact">
            <div class="container">
                <h1 class="con">Contact Us</h1>
                <p>If you have any questions or inquiries, feel free to contact us at <a href="mailto:info@example.com">info@example.com</a>.</p>
            </div>
        </section>
    </div>
   
    <script src="{% static 'js/script-about.js' %}"></script>
</body>
</html>

main/templates/main/index_main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Figtree&family=Libre+Baskerville&family=Open+Sans:wght@700&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/index.css' %}">
</head>
<body>
    
    <div class="container">
        <div class="nav-bar">
            <div class="nav-left">
                <img src="{% static 'images/trident works-fotor-bg-remover-20230818221358.png' %}" alt="Error" class="web-logo">
            </div>
            <div class="nav-right">
                <div class="home">
                    <a href="{% url 'main:index_main' %}">Home</a>
                </div>
                <div class="about">
                    <a href="{% url 'main:about' %}">
                        Our Team
                    </a>
                </div>
                <div class="services">
                    <a href="#bokmark">
                        Services
                    </a>
                </div>
            </div>
        </div>
        <main class="target">
            <img src="{% static 'images/background_urbanization.jpg' %}" alt="Error" class="check_bg">
            <div class="target-content">
                <h1>Trident Works</h1>
                <h3>Local Service Provider</h3>
                <ul>
                    <li>Efficient platform for seamless experience.</li>
                    <li>Enables seamless connections between service providers.</li>
                    <li>Boosts urban efficiency through seamless service exchange.</li>
                </ul>
            </div>
        </main>
        <div class="down-arrow">
            <a href="#bokmark">
                <span><img src="{% static 'images/down-arrow_4196575-fotor-bg-remover-2023081922578.png' %}" alt="" class="arrow1"></span>
                <span><img src="{% static 'images/down-arrow_4196575-fotor-bg-remover-2023081922578.png' %}" alt="" class="arrow2"></span>
                <span><img src="{% static 'images/down-arrow_4196575-fotor-bg-remover-2023081922578.png' %}" alt="" class="arrow3"></span>        
            </a>
        </div>
        <div class="hexagons-for-workers" >
            <img src="{% static 'images/abstract_1.webp' %}" alt="Error" class="wallpaper-gif">
            <main class="text-head-" id="bokmark">Our Services</main>
            
            <main class="tytytyty" >
                <div class="cleaner-card cards">
                    <img src="{% static 'images/cleaner_stick.jpg' %}" alt="Error">
                    <h3>Cleaner works magic, turning messy into marvelous, so you can stay in a fresh paradise</h3>
                </div>
                <div class="cook-card cards">
                    <img src="{% static 'images/chef_stick.jpg' %}" alt="Error">
                    <h3>A culinary maestro, chef conjures delectable wonders, crafting a feast that dances on taste buds.</h3>
                </div>
                <div class="plumber-card cards">
                    <img src="{% static 'images/plumber_stick.jpg' %}" alt="Error">
                    <h3>A plumbing expert, plumber turns pipe predicaments into harmonious flows, ensuring seamless comfort in every drop.</h3>
                </div>
                <div class="electrician-card cards">
                    <img src="{% static 'images/electrician_stick.jpg' %}" alt="Error">
                    <h3>An electrical virtuoso, electrician illuminates spaces with skill, sparking a symphony of power and light.</h3>
                </div>
                <div class="carpenter-card cards">
                    <img src="{% static 'images/carpenter_stick.jpg' %}" alt="Error">
                    <h3>A woodworking virtuoso, carpenter shapes dreams into reality, crafting creations that bring spaces to life.</h3>
                </div>
                <main class="third-tab">
                    <a href="{% url 'main:cleaner' %}">
                        <main class="hexagon first-hex">
                            <div class="for-flex">
                                <img src="{% static 'images/bucket_2946608.png'%}" alt="Error" height="50px" style="margin-top:15px">
                                <span class="overlay cleaner-text">CLEANER</span>
                            </div>
                        </main>
                    </a>
                    <a href="{% url 'main:cook' %}">
                        <main class="hexagon second-hex">
                            <div>
                                <img src="{% static 'images/chef_450166.png'%}" alt="Error" height="50px" style="margin-top:15px; margin-left: 75px;">
                                <span class="overlay cook-text">COOK</span>
                            </div>
                        </main>
                    </a>
                    <a href="{% url 'main:plumber' %}">
                        <main class="hexagon third-hex">
                            <div>
                                <img src="{% static 'images/plumber_3125480.png'%}" alt="Error" height="50px" style="margin-top:15px; margin-left: 75px;">
                                <span class="overlay plumber-text">PLUMBER</span>
                            </div>
                        </main>
                    </a>
                </main>
                <main class="forth-tab">
                    <a href="{% url 'main:elec' %}">
                        <main class="hexagon forth-hex">
                            <div>
                                <img src="{% static 'images/electrician_3707167.png'%}" alt="Error" height="50px" style="margin-top:15px; margin-left: 75px;">
                                <span class="overlay electrician-text">ELECTRICIAN</span>
                            </div>
                        </main>
                    </a>
                    <a href="{% url 'main:carp' %}">
                        <main class="hexagon fifth-hex">
                            <div>
                                <img src="{% static 'images/carpentry_939584.png'%}" alt="Error" height="50px" style="margin-top:15px; margin-left: 75px;">
                                <span class="overlay carpenter-text">CARPENTER</span>
                            </div>
                        </main>
                    </a>                    
                </main>                
            </main>
        </div>
        <!-- ---------------------------------- -->
        <div class="secondlastbar">
            <div class="sl1">
                <a href="{% url 'main:index_main' %}">
                    <img src="{% static 'images/trident works-fotor-bg-remover-20230818221358.png' %}" alt="Error" class="last-left-logo">
                </a>
            </div>
            <div class="sl2">
                <h2>Connect</h2>
                <ul>
                    <li><img src="{% static 'images/location.png' %}" alt="Error" class="location-imag"> 
                        <a href="https://www.google.com/maps/place/Vellore+Institute+of+Technology/@12.9456387,79.1297649,14z/data=!4m10!1m2!2m1!1svit+vellore!3m6!1s0x3bad479f0ccbe067:0xfef222e5f36ecdeb!8m2!3d12.9692232!4d79.1559336!15sCgt2aXQgdmVsbG9yZSIDiAEBkgEScHJpdmF0ZV91bml2ZXJzaXR54AEA!16zL20vMDZzcHNo?entry=ttu">VIT Vellore</a>
                        </li>
                    <li>+1111111111</li>
                    <li>tridentworks@gmail.com</li> 
                </ul>
            </div>
            <div class="sl3">
                <h2>Content</h2>
                <ul>
                    <li><a href="#Bokmark">Home</a> </li>
                    <li>Our Team</li>
                    <li>Services</li>
                </ul>
            </div>
        </div>
        <div class="lastbar">
            <div class="last_leftbar">
                <div class="copyright">&copy; 2023 Your Website. All rights reserved.</div>
                <div><a href="https://www.privacypolicies.com/live/551059e9-d791-45ba-b5b6-def0868537fc" target="_blank">Privacy Policy</a></div>
                <div><a href="https://www.termsandconditionsgenerator.com/live.php?token=CcJUNB79ZpXvCmtgsplWDgNlb7PsClnG" target="_blank">Terms & conditions</a></div>
            </div>
            <div class="last_rightbar">
                <a href="">
                    <img src="{% static 'images/fb.png' %}" alt="Error">
                </a>
                <a href="">
                    <img src="{% static 'images/twit.png' %}" alt="Error">
                </a>
                <a href="">
                    <img src="{% static 'images/li.png' %}" alt="Error">
                </a>
            </div>
        </div>
    </div>   

    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

main/templates/main/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style_main.css' %}">
</head>
<body>
    <div class="container">
        <div class="for-flex">
            <div class="left">
                <h2>Welcome To</h2>
                <h1>TRIDENT
                    <span id='text'></span>
                    <span class='console-underscore' id='console'>|</span>
                </h1>
                <h4>Discover limitless possibilities and embrace top-tier community and environment, enhancing urban living for a smarter, better life. Join us in shaping a brighter future.</h4>
                <div class="buttons">
                    <div class="customer">
                        <img src="{% static 'images/MyApril10.jpg' %}" alt="Error" class="customer-imag">
                        <h3>Customer</h3>
                        <button class="enter">
                            <a href="{% url 'main:index_main' %}">
                                <img src="{% static 'images/enter.png' %}" alt="Error" class="enter-btn">
                            </a>
                        </button>
                    </div>
                    <div class="worker">
                        <img src="{% static 'images/worker_main_page.jpg' %}" alt="Error" class="worker-imag">
                        <h3>Worker</h3>
                        <button class="enter">
                            <a href="{% url 'register' %}">
                                <img src="{% static 'images/enter.png' %}" alt="Error" class="enter-btn">
                            </a>
                            
                        </button>
                    </div>
                </div>
            </div>
            <div class="right">
                <img src="{% static 'images/landing_page_right.jpg' %}" alt="Error" class="logo-right">
            </div>
        </div>
    </div>
    <script src="{% static 'js/newscript.js'%}"></script>
</body> 
</html>